### ISSUE TITLE
The file census_tract_trip_duration_matrix_bycar.csv seems incomplete

### ISSUE THREAD

**Issue by loooffeeeey** [jackmiemie/GMEL#1]
When I run [code/02train_Predictor.py](https://github.com/jackmiemie/GMEL/blob/432166cde82d5ed7ed999294f2f9a03a4c5e39fd/code/02train_Predictor.py)  I got an error 
`IndexError: index 2088 is out of bounds for axis 0 with size 2075`
at
https://github.com/jackmiemie/GMEL/blob/432166cde82d5ed7ed999294f2f9a03a4c5e39fd/code/02train_Predictor.py#L23

I checked that the distm from GMEL-master/data/OSRM/census_tract_trip_duration_matrix_bycar.csv shape (2075, 2168). There should be 2168 census tract so the distance matrix should shape (2168, 2168). 
And then I checked the file GMEL-master/data/OSRM/census_tract_trip_duration_matrix_bycar.csv and found the index representing geocode of census tracts between 5005000 and 5990100 are missing. So the code can't work normally.

Could you please provide complete file of GMEL-master/data/OSRM/census_tract_trip_duration_matrix_bycar.csv? Thanks for reading.

**Comment by jackmiemie** [comment]
Hi,  I have updated a new version of census_tract_trip_duration_matrix_bycar.csv. The issue should be fixed now.
